### PR TITLE
update kotlin and dependency versions, code style adjustment

### PR DESCRIPTION
**Pull request by thepiwo**

### CODE REVIEW

**Comment by florianschmidt1994** [comment]
I think it looks good, but the tests fail. Will investigate

**Comment by florianschmidt1994** [comment]
Unfortunately I don't have resources to check this right now, it seems tricky. I'm not exactly sure why those tests fail now, it does not seem related to what we were changing...

**Comment by thepiwo** [comment]
I don't know why, but it works now

**Comment by florianschmidt1994** [comment]
I tested this and it works. LGTM

**Review by florianschmidt1994 — APPROVED** [review]

**Pull request merged**
